name: flutter_native_timezone
description: A flutter plugin for getting the local timezone of the os.
version: 2.0.0
homepage: https://github.com/pinkfish/flutter_native_timezone

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  js: '>=0.6.3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.flutter_native_timezone
        pluginClass: FlutterNativeTimezonePlugin
      ios:
        pluginClass: FlutterNativeTimezonePlugin
      macos:
        pluginClass: FlutterNativeTimezonePlugin
      web:
        pluginClass: FlutterNativeTimezonePlugin
        fileName: flutter_native_timezone_web.dart
